name: cicd

on:
  push:
    branches:
      - main

  workflow dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
#ci part
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pages
        uses: actions/configure-pages@v2
      - name: build with jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1


deploy:
 environment:
   name: github-pages
   url: ${{ steps.deployment.outputs.page_url }}
 runs-on: ubuntu-latest
 needs: build
 steps:
      - name: Deploy to GitHub Pages
        id: deployment
      # This step checks out the repository to the GitHub Actions runner
        uses: actions/checkout@v1
